"use client";

import {
  TrendingUp, TrendingDown, Diamond, Banknote, Landmark, Bell,
  Target, BarChart3, CheckCircle, Receipt, DollarSign, AlertTriangle,
  CreditCard, ClipboardList, Clock, ShieldCheck, Phone, LifeBuoy,
  PiggyBank, Trophy, CalendarDays, Timer, Siren, Calendar, CalendarRange,
  Bot, Brain, Sparkles, Zap, Star, Link2, Activity, Heart, Users,
  Shield, Home, Car, Stethoscope, Bitcoin, Package, Building2, Map,
  Microscope, Search, AlertCircle, FileText, Sun, Rocket, CircleDollarSign,
  Percent, CalendarCheck, ArrowDownCircle, ArrowUpCircle, Briefcase, MapPin
} from "lucide-react";
import { ReactNode } from "react";

/**
 * Maps emoji strings and named keys to Lucide React icon nodes.
 * Used by KpiCard's auto-resolve feature.
 */
const ICON_MAP: Record<string, ReactNode> = {
  // Emoji → Lucide
  "📈": <TrendingUp size={18} />,
  "📉": <TrendingDown size={18} />,
  "💰": <Banknote size={18} />,
  "💵": <DollarSign size={18} />,
  "💳": <CreditCard size={18} />,
  "🏦": <Landmark size={18} />,
  "🧾": <Receipt size={18} />,
  "₿": <Bitcoin size={18} />,
  "✅": <CheckCircle size={18} />,
  "❌": <AlertCircle size={18} />,
  "⚠️": <AlertTriangle size={18} />,
  "🚨": <Siren size={18} />,
  "🎉": <Trophy size={18} />,
  "💪": <Activity size={18} />,
  "🔴": <AlertCircle size={18} />,
  "👍": <CheckCircle size={18} />,
  "🎯": <Target size={18} />,
  "💎": <Diamond size={18} />,
  "📊": <BarChart3 size={18} />,
  "🔔": <Bell size={18} />,
  "📋": <ClipboardList size={18} />,
  "🛡️": <ShieldCheck size={18} />,
  "🏆": <Trophy size={18} />,
  "⭐": <Star size={18} />,
  "⚡": <Zap size={18} />,
  "✨": <Sparkles size={18} />,
  "🤖": <Bot size={18} />,
  "🧠": <Brain size={18} />,
  "🐖": <PiggyBank size={18} />,
  "🛟": <LifeBuoy size={18} />,
  "📦": <Package size={18} />,
  "📅": <CalendarDays size={18} />,
  "🗓️": <CalendarRange size={18} />,
  "📆": <Calendar size={18} />,
  "⏰": <Clock size={18} />,
  "⏳": <Timer size={18} />,
  "📞": <Phone size={18} />,
  "🏠": <Home size={18} />,
  "🚗": <Car size={18} />,
  "🏥": <Stethoscope size={18} />,
  "🏛️": <Landmark size={18} />,
  "🔗": <Link2 size={18} />,
  "🔒": <Shield size={18} />,
  "📜": <FileText size={18} />,
  "🥇": <Trophy size={18} />,
  "🥈": <Star size={18} />,
  "👨‍👩‍👧‍👦": <Users size={18} />,
  "💼": <Briefcase size={18} />,
  "🚀": <Rocket size={18} />,
  "❤️": <Heart size={18} />,
  "🌟": <Star size={18} />,
  "📌": <MapPin size={18} />,
  "🔭": <Microscope size={18} />,
  "➗": <Percent size={18} />,
  "🧑‍🤝‍🧑": <Users size={18} />,

  // Named keys → Lucide (for new code using string keys)
  trendingUp: <TrendingUp size={18} />,
  trendingDown: <TrendingDown size={18} />,
  diamond: <Diamond size={18} />,
  banknote: <Banknote size={18} />,
  landmark: <Landmark size={18} />,
  bell: <Bell size={18} />,
  target: <Target size={18} />,
  barChart: <BarChart3 size={18} />,
  checkCircle: <CheckCircle size={18} />,
  receipt: <Receipt size={18} />,
  dollarSign: <DollarSign size={18} />,
  alertTriangle: <AlertTriangle size={18} />,
  creditCard: <CreditCard size={18} />,
  clipboard: <ClipboardList size={18} />,
  clock: <Clock size={18} />,
  shieldCheck: <ShieldCheck size={18} />,
  phone: <Phone size={18} />,
  lifeBuoy: <LifeBuoy size={18} />,
  piggyBank: <PiggyBank size={18} />,
  trophy: <Trophy size={18} />,
  calendar: <CalendarDays size={18} />,
  calendarRange: <CalendarRange size={18} />,
  timer: <Timer size={18} />,
  siren: <Siren size={18} />,
  heart: <Heart size={18} />,
  users: <Users size={18} />,
  shield: <Shield size={18} />,
  home: <Home size={18} />,
  car: <Car size={18} />,
  stethoscope: <Stethoscope size={18} />,
  bitcoin: <Bitcoin size={18} />,
  package: <Package size={18} />,
  building: <Building2 size={18} />,
  map: <Map size={18} />,
  microscope: <Microscope size={18} />,
  search: <Search size={18} />,
  alertCircle: <AlertCircle size={18} />,
  fileText: <FileText size={18} />,
  sun: <Sun size={18} />,
  rocket: <Rocket size={18} />,
  percent: <Percent size={18} />,
  calendarCheck: <CalendarCheck size={18} />,
  link: <Link2 size={18} />,
  sparkles: <Sparkles size={18} />,
  briefcase: <Briefcase size={18} />,
  mapPin: <MapPin size={18} />,
  zap: <Zap size={18} />,
  star: <Star size={18} />,
  bot: <Bot size={18} />,
  brain: <Brain size={18} />,
  activity: <Activity size={18} />,
  income: <ArrowDownCircle size={18} />,
  expense: <ArrowUpCircle size={18} />,
};

/**
 * Resolves an icon string (emoji or named key) to a Lucide ReactNode.
 * If the input is already a ReactNode, returns it as-is.
 */
export function resolveIcon(icon: string | ReactNode, fallback?: ReactNode): ReactNode {
  if (typeof icon !== "string") return icon;
  return ICON_MAP[icon] || fallback || <CircleDollarSign size={18} />;
}
